# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages
sudo: false
warnings_are_errors: false
r_check_args: "--no-build-vignettes --no-manual --as-cran --no-examples"

r: 3.6.1    
bioc_packages:
  - GenomicRanges    

r_github_packages:
  - mskilab/gUtils

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - export R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE

script:
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - travis_wait Rscript -e 'covr::codecov()'


notifications:
  email:
    on_success: change
    on_failure: change
